### PR TITLE
Govcloud

### PR DESCRIPTION
**Pull request by DemetriusTsitrelis**
Add GovCloud region and associated Amazon Linux 1 AMI

### CODE REVIEW

**Comment by taylorr4** [comment]
Thanks for submitting this, @DemetriusTsitrelis.

@JamesSWiggins, does this change look good to you? Thanks for your input.

**Comment by JamesSWiggins** [comment]
Thanks, @taylorr4.

@DemetriusTsitrelis Thanks for the pull request!  Super neat that you're using this in GovCloud.  Did it work just by adding the AMI reference?

I'm confused by some of the other changes you made, specifically removing many parameters from being passed into the redcapelasticbeanstalk template.  This template depends on those inputs.  What was the purpose of removing them?

**Comment by DemetriusTsitrelis** [comment]
@JamesSWiggins 
Sorry James, that last commit was a mistake; I only wanted to add the AMI for GovCloud.
Note that while it works, hoping that the temp instance will be changed to use Amazon Linux 2 in the future.

**Comment by taylorr4** [comment]
@JamesSWiggins what do you think of these changes (after @DemetriusTsitrelis reverted the code that you had questions about)? Thanks!

**Comment by JamesSWiggins** [comment]
@taylorr4 @DemetriusTsitrelis Apologies for the delay here.  Yes, I've taken the gov-cloud portions and am incorporating them into an update that will also include the REDCap application download API.  Thanks for contributing, Demetrius!!

**Comment by taylorr4** [comment]
Thanks so much, @JamesSWiggins!

**Comment by MSIH** [comment]
If the changes in this pull request have been incorporated into the main branch, could this pull request be closed?

**Pull request closed without merging**
