### PR TITLE
Update upgrade-aws-eb.sh

### PR DESCRIPTION
**Pull request by d2205**
Latest method to retrieve instance metadata. On Amazon Linux 2023, upgrades within REDCap will not complete using the old method to retrieve INSTANCE_ID, ENVIRONMENT_NAME and REGION.

### CODE REVIEW

**Comment by taylorr4** [comment]
Looks good. Thanks, @d2205!

**Comment by d2205** [comment]
@taylorr4 Rob, 
I believe this change also needs to happen on the REDCap package that is downloaded from version upgrades.

I noticed after every version upgrade, this modification gets reset by the old _upgrade-aws-eb.sh_  file that comes inside redcap_vx.x.x.

The only way for me to successfully upgrade is to:
Download the currently deployed application version package from ElasticBeanstalk.
Edit _upgrade-aws-eb.sh_, reupload and redeploy.

After these steps, I can successfully perform a REDCap version upgrade. However, next update attempt won't work because _upgrade-aws-eb.sh_ is rewritten with the original file containing the old method to retrieve INSTANCE_ID, ENVIRONMENT_NAME and REGION.

Hopefully that makes sense! :)

Thanks,
Danilo

**Comment by taylorr4** [comment]
@d2205 Thanks so much for letting us know about this. We'll update this file in REDCap in this week's release: 14.5.23 LTS and 14.8.0 Standard.

> Bug fix: If using the AWS CloudFormation deployment of REDCap, the REDCap upgrade process might mistakenly fail or have issues due to the "upgrade-aws-eb.sh" file inside the REDCap source code not being up-to-date with the same file stored in the GitHub repo for REDCap's AWS CloudFormation (https://github.com/vanderbilt-redcap/redcap-aws-cloudformation/). The file inside REDCap has now been updated to match the GitHub file.

**Comment by d2205** [comment]
@taylorr4 Perfect! Thank you.

**Pull request merged**
