### PR TITLE
Update 02-rc-elasticbeanstalk.yaml

### PR DESCRIPTION
**Pull request by nicholasbcarr**

### CODE REVIEW

**Comment by nicholasbcarr** [comment]
j

**Comment by nicholasbcarr** [comment]
ok

**Comment by AaronJackson** [comment]
@nicholasbcarr I believe this change introduced a new issue

> Resource handler returned message: "The Parameter Group ... with DBParameterGroupFamily aurora-mysql5.7 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-mysql8.0 (Service: Rds, Status Code: 400, Request ID: ...)" (RequestToken: ..., HandlerErrorCode: InvalidRequest)

https://redcap.vanderbilt.edu/community/post.php?id=213522

I'm currently unable to deploy redcap

**Comment by nicholasbcarr** [comment]
Aloha Aaron,

Please check the thread. I had this same issue when deploying in the west
region due to resource differences with the east region where the template
was designed to be use with no modifications.
I will be sure to check the thread when I get to work in the morning
because it's a relatively easy fix.

Nick

**Pull request closed without merging**
