### PR TITLE
use query to get volume id of log drive

### PR DESCRIPTION
**Pull request by lsefabian**
This change should simplify and make less error-prone getting the volume id of the disk created to hold logs

### CODE REVIEW

**Comment by taylorr4** [comment]
Can anyone confirm the validity of this change since i'm not very knowledgeable on the scripting side of this? @JamesSWiggins

**Comment by taylorr4** [comment]
@JamesSWiggins, i know you're busy, but if you have a moment to verify the changes in this PR and [also this one](https://github.com/vanderbilt-redcap/redcap-aws-cloudformation/pull/17), we'd be very appreciative. thanks!

**Comment by JamesSWiggins** [comment]
Apologies for the delay.  This is another great simplification.  Thanks @nplse !!  @taylorr4

**Comment by taylorr4** [comment]
Thanks, @JamesSWiggins, for your input.

@lsefabian can you resolve the code conflict here (now that i've already merged PR 17). I'm not sure i know exactly how to resolve it. Then i will merge this. Thanks!

**Comment by lsefabian** [comment]
Thanks @JamesSWiggins @taylorr4 

I've merged PR17 in and all looks fine to me

**Comment by taylorr4** [comment]
@lsefabian thanks! And i've also updated this file's doppelganger in S3 so that it's all in sync.

**Pull request merged**
